interface ZIF_YTODO_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF YTODO,
 CREATE_YTODO                   TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EE9B89E95DB5D65AB34',
 DELETE_YTODO                   TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EE9B89E95DB5D662B34',
 LOCK_YTODO                     TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EE9B89E95DB5D64EB34',
 SAVE_YTODO                     TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EE9B89E95DB5D66AB34',
 UNLOCK_YTODO                   TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EE9B89E95DB5D652B34',
 UPDATE_YTODO                   TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EE9B89E95DB5D65EB34',
 VALIDATE_YTODO                 TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EE9B89E95DB5D666B34',
      END OF YTODO,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF YTODO,
        BEGIN OF LOCK_YTODO,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_YTODO,
        BEGIN OF UNLOCK_YTODO,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_YTODO,
      END OF YTODO,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF YTODO,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EE9B89E95DB5D64CB34',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EE9B89E95DB5D648B34',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EE9B89E95DB5D658B34',
      END OF YTODO,
      BEGIN OF YTODO_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EE9B89E95DB5D670B34',
      END OF YTODO_LOCK,
      BEGIN OF YTODO_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EE9B89E95DB5D66EB34',
      END OF YTODO_MESSAGE,
      BEGIN OF YTODO_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EE9B89E95DB5D672B34',
      END OF YTODO_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF YTODO,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF YTODO,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0242AC1100021EE9B89E95DB5D63EB34' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'YTODO' .
  constants:
    BEGIN OF SC_GROUP,
 DRAFT_CONSISTENCY              TYPE /BOBF/OBM_GROUP_KEY VALUE '0242AC1100021EE9B89E95DB5D676B34',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 YTODO                          TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100021EE9B89E95DB5D642B34',
 YTODO_LOCK                     TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100021EE9B89E95DB5D64AB34',
 YTODO_MESSAGE                  TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100021EE9B89E95DB5D646B34',
 YTODO_PROPERTY                 TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100021EE9B89E95DB5D656B34',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF YTODO,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0242AC1100021EE9B89E95DB5D644B34',
      END OF YTODO,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_STATUS_VARIABLE,
      BEGIN OF YTODO,
 DRAFT_CONSISTENCY_STATUS       TYPE /BOBF/STA_VAR_KEY VALUE '0242AC1100021EE9B89E95DB5D674B34',
      END OF YTODO,
    END OF SC_STATUS_VARIABLE .
endinterface.
